"""Add jobs field for user

Revision ID: 1a91ad3528b4
Revises: dbbf2049e76d
Create Date: 2022-11-13 23:09:22.385175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a91ad3528b4'
down_revision = 'dbbf2049e76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_school_performances',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('math', sa.Integer(), nullable=True),
    sa.Column('physics', sa.Integer(), nullable=True),
    sa.Column('chemistry', sa.Integer(), nullable=True),
    sa.Column('biology', sa.Integer(), nullable=True),
    sa.Column('literature', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('geography', sa.Integer(), nullable=True),
    sa.Column('phylosophy', sa.Integer(), nullable=True),
    sa.Column('art', sa.Integer(), nullable=True),
    sa.Column('foreign_language', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('jobs', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jobs')
    op.drop_table('user_school_performances')
    # ### end Alembic commands ###
