"""add soft delete column

Revision ID: decdc4cf4767
Revises: 1a91ad3528b4
Create Date: 2022-11-14 15:26:53.992396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decdc4cf4767'
down_revision = '1a91ad3528b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_school_performances', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'user_school_performances', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_constraint(None, 'user_school_performances', type_='foreignkey')
    op.drop_column('user_school_performances', 'deleted_at')
    # ### end Alembic commands ###
